package guldilin.errors;

public enum ErrorCode {
    ENTRY_NOT_FOUND,
    FILTER_TYPE_NOT_SUPPORTED,
    FILTER_TYPE_NOT_FOUND,
    CONTENT_TYPE_NOT_SUPPORTED,
    VALIDATION_ERROR,
    JSON_SYNTAX_ERROR,
    INTERNAL_SERVER_ERROR,
    METHOD_NOT_SUPPORTED,
    RESOURCE_NOT_FOUND,
    INCORRECT_NUMBER_FORMAT,
    ENUM_CONSTANT_NOT_FOUND,
    WRONG_DATE_FORMAT,
    SORTING_FIELD_ERROR,
}
